# Generated by Django 4.1.3 on 2023-01-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_user_paymentcard_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='preferred_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='loans.currency'),
        ),
    ]
