# Generated by Django 4.1.3 on 2022-12-19 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezaim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='preferred_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='ezaim.currency'),
            preserve_default=False,
        ),
    ]
