# Generated by Django 4.1.3 on 2022-12-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezaim', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasportData',
            new_name='PassportData',
        ),
    ]
