# Generated by Django 4.1.3 on 2022-12-19 16:59

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ezaim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='token',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezaim.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
