# Generated by Django 4.1.3 on 2022-12-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezaim', '0002_loan_isactive_alter_usersettings_preferred_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
