# Generated by Django 4.1.3 on 2022-12-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezaim', '0002_paymentcard_token_orderuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='csv',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='number',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='valid_through',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
